export const FETCH_SUCCESS = 'FETCH_SUCCESS';

export const FETCH_FAILED = 'FETCH_FAILED';

export const POST_SUCCESS = 'POST_SUCCESS';

export const POST_FAILED = 'POST_FAILED';

export const PUT_SUCCESS = 'PUT_SUCCESS';

export const PUT_FAILED = 'PUT_FAILED';

export const DELETE_SUCCESS = 'DELETE_SUCCESS';

export const DELETE_FAILED = 'DELETE_FAILED';

export const LOGIN_FAILED = 'LOGIN_FAILED';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const SIGNUP_FAILED = 'SIGNUP_FAILED';

export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';

export const SUBMIT_SUCCESS = 'SUBMIT_SUCCESS';

export const SET_CURRENT_MARKER_SUCCESS = 'SET_CURRENT_MARKER_SUCCESS';
