export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';

export const FETCH_ACCIDENTS_SUCCESS = 'FETCH_ACCIDENTS_SUCCESS';

export const LOGIN_CHECK = 'LOGIN_CHECK';

export const LOGIN_FAILED = 'LOGIN_FAILED';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const SIGNUP_FAILED = 'SIGNUP_FAILED';

export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';

export const SUBMIT_SUCCESS = 'SUBMIT_SUCCESS';

export const SET_CURRENT_MARKER_SUCCESS = 'SET_CURRENT_MARKER_SUCCESS';

export const GET_ID_SUCCESS = 'GET_ID_SUCCESS';

export const GET_IMG_SUCCESS = 'GET_IMG_SUCCESS';

export const DUMP_ACCIDENT_SUCCESS = 'DUMP_ACCIDENT_SUCCESS';
